<?php
echo "name: $theme_name Dark\n";
echo "accent: '$B4T_A12'\n";
echo "background: '$B4T_b2'\n";
echo "foreground: '$B4T_b14'\n";
echo "details: darker\n";
echo "terminal_colors:\n";
echo "  normal:\n";
echo "    black: '$B4T_b2'\n";
echo "    red: '$B4T_D11'\n";
echo "    green: '$B4T_A12'\n";
echo "    yellow: '$B4T_A17'\n";
echo "    blue: '$B4T_B16'\n";
echo "    magenta: '$B4T_C15'\n";
echo "    cyan: '$B4T_A15'\n";
echo "    white: '$B4T_b22'\n";
echo "  bright:\n";
echo "    black: '$B4T_b0'\n";
echo "    red: '$B4T_D16'\n";
echo "    green: '$B4T_A18'\n";
echo "    yellow: '$B4T_A20'\n";
echo "    blue: '$B4T_B21'\n";
echo "    magenta: '$B4T_C17'\n";
echo "    cyan: '$B4T_B20'\n";
echo "    white: '$B4T_b23'\n";
